### ISSUE TITLE
fill-keymap is still an existing function ?

### ISSUE THREAD

**Issue by PierreR** [tarleb/evil-rebellion#1]
`fill-keymap` does not seem to exist in emacs-24.3.1

https://github.com/tarleb/evil-rebellion/blob/master/evil-magit-rebellion.el#L28

It looks like this is needed:
https://github.com/sandbox/emacs/blob/master/setting-functions.el

**Comment by tarleb** [comment]
Thanks for the report, I have that function in a different packagee and didn't notice that things stop working without it.  It's not really needed, and I'm going to correct the respective code over the next few days.

Please note, however, that lately the project didn't get as much of my time as it deserves, so a lot of things will not work correctly.  I'll take your report as extra motivation to make it useable again.

In the meantime, you might want to look at [evil-god-state](https://github.com/gridaphobe/evil-god-state) which already does a lot of what I was trying to achive when starting the evil rebellion.  I plan to leverage evil-god-state features to add functionality to evil-rebellion in the future.

**Comment by tarleb** [comment]
Thanks again for reporting the issue, should be fixed now.
