### ISSUE TITLE
commit binding for evil-magit-rebellion

### ISSUE THREAD

**Issue by PierreR** [tarleb/evil-rebellion#2]
I can't find the binding for the commit action on the `magit-status-mode`

Would it make sense to rebind `c` to `magit-commit` for that mode ?

Cheers

**Comment by tarleb** [comment]
`c` is already defined for `magit-mode`. `magit-status-mode` has `magit-mode` as its parent mode, meaning that also it inherits its key bindings.  Everything should work, please let me know if it doesn't.

**Comment by PierreR** [comment]
I believe `c` is rebound here: https://github.com/tarleb/evil-rebellion/blob/master/evil-magit-rebellion.el#L66
which does not make much sense I think.
I have rebound them locally but as you suggested I should probably delete the binding.

**Comment by tarleb** [comment]
Please try it in it's current state and let me know about the result.

The current keybindings are taken almost verbatim from the original magit code and then changed where necessary. `c` is one definition that remains untouched.  While I agree that the current binding is a bit irritating, I still believe that it does in fact make sense.  Could you explain why you'd like to change it?

**Comment by tarleb** [comment]
Just realized: which magit version are you using? I'm using version v1.2.1 packed with my OS, maybe things work differently in newer versions.

**Comment by PierreR** [comment]
Well I am using the version from `melpa.stable`. It looks quite different indeed as even the binding `magit-log-edit` does not exist for me (apparently it is a magit plugin):
https://github.com/magit/magit/blob/fcb00fb3f5a6bc37de3a7b9abf5b3a5ef3814438/magit.el#L68

**Comment by tarleb** [comment]
> Well I am using the version from `melpa.stable`. It looks quite different
> indeed as even the binding `magit-log-edit` does not exist for me (apparently
> it is a magit plugin):

That explains it, thank you.  I'll try to fix it (and I'll happily
accept pull requests, too ;).

## 

Albert Krewinkel
GPG: 8eed e3e2 e8c5 6f18 81fe  e836 388d c0b2 1f63 1124
